#include<stdlib.h>
#include<stdio.h>		// scanf
#include<math.h>
#include<time.h>
#include"ar_reli.c"


int
main (int args, char *argv[])
{
  printf ("\nTask1 [Nx1]: array manipulations \n| clang -lm in Termux \n| gcc -lm in terminal\n\n");
  printf ("T3: real, I3:rnd, M1:inserion\n");

  srand (time (0));
  printf ("Try to guess rnd number, \
that will be generated by this program...\nGuess number is ?=");
  int guess_number;
  if (scanf ("%d", &guess_number) != 1)
    return 0;
  printf ("%d", guess_number);
  int size = rndmg (5, 20);
  int matrix[size];
  introduction (matrix, size, guess_number);
  imprinted (matrix, size);
  inception (matrix, size);

  return 0;
}
